//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTest.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Windows.Media;
    using System.Windows.Media.Imaging;

    public partial class Charity
    {
        public int CharityId { get; set; }
        public string CharityName { get; set; }
        public string CharityDescription { get; set; }
        public string CharityLogo { get; set; }
        private ImageSource charityImage;
        public ImageSource CharityImage
        {
            get
            {
                if (charityImage == null)
                {
                    BitmapImage bitmapImage = new BitmapImage();
                    bitmapImage.BeginInit();
                    bitmapImage.UriSource = new Uri(@"..\..\Resource\" + CharityLogo, UriKind.RelativeOrAbsolute);
                    bitmapImage.EndInit();
                    
                    charityImage = bitmapImage;
                }
                return charityImage;
            }
            set
            {
                charityImage = value;
            }
        }
        public bool IsActive { get; set; }
    }
}
