//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceKitOption
    {
        public string RaceKitOptionId { get; set; }
        public string RaceKitOption1 { get; set; }
        public decimal Cost { get; set; }
    }
}
