//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationStatus
    {
        public byte RegistrationStatusId { get; set; }
        public string RegistrationStatus1 { get; set; }
    }
}
